enum PopularCreator: String, CaseIterable {
    case jamieOliver = "Jamie Oliver"
    case yotamOttolenghi = "Yotam Ottolenghi"
    case anthonyBourdain = "Anthony Bourdain"
    case nusretGökçe = "Nusret Gökçe"
    case gordonRamsay = "Gordon Ramsay"
    case massimoBottura = "Massimo Bottura"
    case christinaTosi = "Christina Tosi"
    case sanjeevKapoor = "Sanjeev Kapoor"
    case joëlRobuchon = "Joël Robuchon"
    case alainDucasse = "Alain Ducasse"
    case ferranAdrià = "Ferran Adrià"
    case thomasKeller = "Thomas Keller"
    case danielHumm = "Daniel Humm"
    case marthaStewart = "Martha Stewart"
}
